image: maven:latest

stages:
  - build
  - deploy

before_script:
  - apt-get update
  - apt-get install -y ant git

build_project:
  stage: build
  script:
    - git --version
    - ant -version
    - cd retailJavaCustom
    - git init
    - |
      if git remote get-url origin; then
        git remote set-url origin https://ribesh.shrestha:${ACCESS_TOKEN}@gitlab.cas.com.np/devops/build_project_file.git
      else
        git remote add origin https://ribesh.shrestha:${ACCESS_TOKEN}@gitlab.cas.com.np/devops/build_project_file.git
      fi
    - git remote -v
    - git fetch origin
    - git pull origin main --allow-unrelated-histories
    - pwd
    - ls -al
    - ant compile
    - ant jar
  artifacts:
    paths:
      - retailJavaCustom/dist/*.jar
    expire_in: 1 week

deploy_to_registry:
  stage: deploy
  dependencies:
    - build_project
  image: curlimages/curl:latest
  script:
    - echo "Deploying to GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN"
    - ls retailJavaCustom/dist/*.jar
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file retailJavaCustom/dist/*.jar "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/retailJavaCustom/${CI_COMMIT_REF_NAME}/retail.jar"'
    - echo "Finished !!!"
