image: frekele/ant

stages:
  - build
  - deploy

variables:
  GIT_STRATEGY: clone

before_script:
  # Ensure Ant is installed
  - apt-get update && apt-get install -y ant

build_project:
  stage: build
  script:
    - ls -la
    - cd retailJavaCustom
    - ant compile
    - ant jar
  artifacts:
    paths:
      - retailJavaCustom/dist/*.jar
    expire_in: 1 week

deploy_to_registry:
  image: maven:latest
  stage: deploy
  dependencies:
    - build_project
  before_script:
    - ls -la
    - cd retailJavaCustom
  script:
    - echo "Deploying to GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN"
    - ls retailJavaCustom/dist/*.jar
    - mvn deploy -s retailJavaCustom/ci_settings.xml
