image: frekele/ant
# image: alpine:latest

stages:
  - build
  - deploy

build_project:
  stage: build
  before_script:
  # Ensure Ant is installed
  - apt-get update && apt-get install -y ant 
  - apt-get install -y curl tar xz-utils || true
  - curl -L https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.45.2.tar.gz -o git.tar.gz
  - tar -zxf git.tar.gz
  - cp -r git-2.45.2/* /usr/local/
  - ln -s /usr/local/git/bin/* /usr/local/bin/
  - git --version  # Verify git installation   
  # - apk add --no-cache git openjdk11-jdk ant
  - cd retailJavaCustom
  - git config --global user.name "ribesh.shrestha"
  - git config --global user.email "ribesh.shrestha@cas.com.np"
  - git init
  - git remote set-url origin https://ribesh.shrestha:${ACCESS_TOKEN}@gitlab.cas.com.np/devops/build_project_file.git
  - git remote -v
  - git fetch origin
  - git pull origin main --allow-unrelated-histories

  script:
    - ls -la
    - cd retailJavaCustom
    - ant compile
    - ant jar
  
  artifacts:
    paths:
      - retailJavaCustom/dist/*.jar
    expire_in: 1 week

deploy_to_registry:
  stage: deploy
  dependencies:
    - build_project
  image: curlimages/curl:latest

  script:
    - echo "Deploying to GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN"
    - ls retailJavaCustom/dist/*.jar
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file retailJavaCustom/dist/*.jar "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/retailJavaCustom/${CI_COMMIT_REF_NAME}/retail.jar"'
    - echo "Finished !!!"
 

