# image: bitnami/git:latest
image: maven:3.8.1-jdk-11

stages:
  - build
  - deploy

before_script:
  - apt-get update
  - apt-get install -y ant git

build_project:
  stage: build
  script:
    - git --version
    - ant -version
    - mkdir files
    - cd files
    - git init
    # - |
    #   if git remote get-url origin; then
    #     git remote set-url origin https://ribesh.shrestha:${ACCESS_TOKEN}@gitlab.cas.com.np/devops/build_project_file.git
    #   else
    #     git remote add origin https://ribesh.shrestha:${ACCESS_TOKEN}@gitlab.cas.com.np/devops/build_project_file.git
    #   fi
    # - git remote -v
    # - git fetch --all
    # - git pull origin main
    # - git log origin/main
    - git config --global user.name "ribesh.shrestha"
    - git config --global user.email "ribesh.shrestha@cas.com.np"
    - git clone "https://ribesh.shrestha:${ACCESS_TOKEN}@gitlab.cas.com.np/devops/build_project_file.git"
    - ls -al
    - ls -al ../
    - cp -r build_project_file/* ../retailJavaCustom
    - pwd
    - cd ../retailJavaCustom
    - ls -al
    - ls -al nbproject
    - ls -al nbproject/private
    - ls -al lib
    - ant compile
    - ant jar
  artifacts:
    paths:
      - retailJavaCustom/dist/*.jar
    expire_in: 1 week

deploy_to_registry:
  stage: deploy
  dependencies:
    - build_project
  image: curlimages/curl:latest
  script:
    - echo "Deploying to GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN"
    - ls retailJavaCustom/dist/*.jar
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file retailJavaCustom/dist/*.jar "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/retailJavaCustom/${CI_COMMIT_REF_NAME}/retail.jar"'
    - echo "Finished !!!"
