
image: frekele/ant
stages:
  - build
  - deploy
variables:
  GIT_STRATEGY: clone
before_script:
  # Ensure Ant is installed
  - apt-get update && apt-get install -y ant
build_project:
  stage: build
  script:
    - ls -la
    - cd retailJavaCustom
    - ant compile
    - ant jar
  artifacts:
    paths:
      - retailJavaCustom/dist/*.jar
    expire_in: 1 week

deploy_to_registry:
    stage: deploy
    dependencies:
     - build
    script:
    - echo "Deploying to GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN"
    - ls retailJavaCustom/build/*.jar
    - ant deploy -buildfile build.xml
