image: frekele/ant

stages:
  - build
  - deploy

build_project:
  stage: build
  before_script:
  # Ensure Ant is installed
  - apt-get update && apt-get install -y ant
  

  script:
    - ls -la
    - cd retailJavaCustom
    - ant compile
    - ant jar
  artifacts:
    paths:
      - retailJavaCustom/dist/*.jar
    expire_in: 1 week

# deploy_to_registry:
#   image: maven:latest
#   stage: deploy
#   dependencies:
#     - build_project
#   script:
#     - echo "Deploying to GitLab Container Registry..."
#     - echo "$CI_JOB_TOKEN"
#     - cd retailJavaCustom
#     - ls dist/*.jar
#     - mvn clean deploy -s ci_settings.xml

deploy_to_registry:
  stage: deploy
  dependencies:
    - build_project
  # image: curlimages/curl:latest
  image: alpine:latest
  before_script:
    - apk add git curl
    # - cd retailJavaCustom
    # - ping gitlab.cas.com.np
    # - git config --global user.name "ribesh.shrestha"
    - git init
    - git remote set-url origin https://ribesh.shrestha:${ACCESS_TOKEN}@gitlab.cas.com.np/devops/build_project_file.git
    # - git remote set-url origin https://gitlab.cas.com.np/devops/build_project_file.git
    - git remote -v
    # - git branch --set-upstream-to=origin/main main
    # - git fetch origin
    - git config pull.rebase false
    - git pull origin main --allow-unrelated-histories


  script:
    - echo "Deploying to GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN"
    - ls retailJavaCustom/dist/*.jar
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file retailJavaCustom/dist/*.jar "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/retailJavaCustom/${CI_COMMIT_REF_NAME}/retail.jar"'
    - echo "Finished !!!!"
 

