image: frekele/ant

stages:
  - build
  - deploy
  - deploy_war

# before_script:
#   - apt-get update && apt-get install -y ant zip curl

build_project:
  stage: build
  script:
    - cd retailJavaCustom
    - ant compile
    - ant jar
  artifacts:
    paths:
      - retailJavaCustom/dist/*.jar
    expire_in: 1 week

deploy_registry:
  stage: deploy
  dependencies:
    - build_project
  image: alpine
  before_script:
    - apk update && apk add --no-cache zip curl
  script:
    - echo "Deploying to GitLab Container Registry..."
    - echo "$CI_JOB_TOKEN"
    - ls retailJavaCustom/dist/*.jar
    - mv retailJavaCustom/dist/MyDMS.jar retailJavaCustom/dist/Retail.jar
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file retailJavaCustom/dist/*.jar "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/retailJavaCustom/${CI_COMMIT_REF_NAME}/Retail.jar"'
    # - mv retailJavaCustom/dist/MyDMS.jar retailJavaCustom/dist/Retail.jar
    - cp -r retailJavaCustom/dist/Retail.jar retail/WEB-INF/lib
    - ls retail/WEB-INF/lib
    - zip -r retail.zip retail
    - mv retail.zip LOS_Retail.war
    - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file LOS_Retail.war "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/retail/${CI_COMMIT_REF_NAME}/LOS_Retail.war"'
    - echo "Finished !!!"
